### PR TITLE
add bump map for earth

### PR DESCRIPTION
**Pull request by xfjcox2007**

### CODE REVIEW

**Review by JiangyunWang — COMMENTED** [review]
I don't see the Sun

**Review by motion-zhang — APPROVED** [review]

**Review by motion-zhang — CHANGES_REQUESTED** [review]
Can't see the sun. sunMesh not added to the scene.

**Comment by xfjcox2007** [comment]
Missed sun6.png before. 
I added sun6.png now, now you should be able to see the sun

**Review by JiangyunWang — APPROVED** [review]
Good to on board

**Review by motion-zhang — APPROVED** [review]

**Pull request merged**
